### ISSUE TITLE
Get  items or elements selected

### ISSUE THREAD

**Issue by ruralkan** [IswPolymerElements/isw-dropdown-menu#7]
How I can get and use the items or Elements selected?

**Comment by rene-lindner-isw** [comment]
The dropdown is using an paper-listbox for selection, the selected values are 1:1 bound inside the dropdown, so you can basically use the dropdown like a listbox.

Hope this will get clearer when webcomponents.org supports Polymer 2.0 documentation :)

Available properties from listbox: attrForSelected, multi, selected, selectedItem, selectedItems, selectedValues.

https://www.webcomponents.org/element/polymerelements/paper-listbox/paper-listbox

**Comment by rene-lindner-isw** [comment]
There is already a demo for webcomponents.org 2.0 API Support:
https://www.webcomponents.org/element/IswPolymerElements/isw-dropdown-menu/elements/isw-dropdown-menu?analyzer
